version: '3.8'

services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./cassandra/data:/var/lib/cassandra
    networks:
      - spark_net

  spark-master:
    image: bitnami/spark:3.4
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8081:8080"
    networks:
      - spark_net

  spark-worker:
    image: bitnami/spark:3.4
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    networks:
      - spark_net

  zeppelin:
    image: apache/zeppelin:0.10.1
    container_name: zeppelin
    ports:
      - "8080:8080"
    environment:
      - ZEPPELIN_NOTEBOOK_DIR=/zeppelin/notebook
    volumes:
      - ./zeppelin/notebooks:/zeppelin/notebook       # Delte Zeppelin-notater
      - ./data:/data                                 # Delt data-volum
    depends_on:
      - spark-master
      - cassandra
    networks:
      - spark_net

networks:
  spark_net:
    driver: bridge
